#!/bin/bash

# For this script to run, you need to have inotify tools installed.
# You can install it by running the command:
# sudo apt-get install inotify-tools


if [ -z "$1" ]; then
    echo "Usage: mon <path_to_script>"
    exit 1
fi

path="$1"

while true; do
   
    file_changed=$(inotifywait -e modify -q --format '%w%f' "$path")

    
    if [ -n "$file_changed" ]; then
        
        clear
        
        python3 "$path"
    fi

   
    sleep 1
done
