#!/bin/bash


if [ -z "$1" ]; then
    TARGET_IP="localhost"  
else
    TARGET_IP="$1"  
fi


scan_ports() {
    local START_PORT=$1
    local END_PORT=$2
    echo "Scanning ports $START_PORT-$END_PORT on $TARGET_IP..."
    nmap -p $START_PORT-$END_PORT --max-retries 3 --min-rate 100 --open -Pn $TARGET_IP
    echo "Done scanning ports $START_PORT-$END_PORT."
    sleep 2 
}


for ((PORT=1; PORT<=65535; PORT+=1000)); do
    END_PORT=$((PORT + 999))
    if [ $END_PORT -gt 65535 ]; then
        END_PORT=65535 
    fi
    scan_ports $PORT $END_PORT
done
